<?php
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?','blackwell'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'blackwell'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'blackwell'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'blackwell'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'blackwell'));
define('NOTHING_FOUND',__('Nothing Found here', 'blackwell'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria.', 'blackwell'));
define('CATEGORIES',__('Categories', 'blackwell'));
define('ARCHIVES',__('Archives', 'blackwell'));
define('BLOG_ARCHIVES',__('Blog Archives', 'blackwell'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'blackwell'));
define('PAGE',__('Page %s', 'blackwell'));
define('SEARCH_RESULT',__('Search Results for: %s', 'blackwell'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'blackwell'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'blackwell'));
define('LCN_MAP',__('Location Map','blackwell'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'blackwell'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'blackwell'));
define('ABOUT',__('About: %s', 'blackwell'));
define('HOME_TEXT',__('Home', 'blackwell'));
define('THIS_ENTRY_WAS_POSTED_IN',__('This entry was posted in %1$s','blackwell'));
define('PERMALINK',__('permalink','blackwell'));
define('BOOKMARK_THE',__('Bookmark the','blackwell'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'blackwell'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'blackwell'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'blackwell'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'blackwell'));
define('SMT_CMT',__('Submit Comment', 'blackwell'));
define('LV_CMT',__('Leave a Comment', 'blackwell'));
define('OLDER_POSTS',__('&larr; Older posts', 'blackwell'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'blackwell'));
define('PREV_POST',__(' Previous Post', 'blackwell'));
define('NEXT_POST',__('Next Post ', 'blackwell'));
define('READ_MORE',__('Read More', 'blackwell'));
define('SND_MSG',__('Send Your Message', 'blackwell'));
define('RETURN_TO',__('Return to %s', 'blackwell'));
define('BY_AUTHOR',__('By %2$s', 'blackwell'));
define('VIEW_ALL_POST_BY',__('View all posts by %s', 'blackwell'));
define('PUBLISHED_BY',__('Published %2$s', 'blackwell'));
define('FULL_SIZE_IS_PIXEL',__('Full size is %s pixels', 'blackwell'));
define('LINK_TO_FULL_SIZE_IMAGE',__('Link to full-size image', 'blackwell'));
define('EDIT_TEXT',__('Edit', 'blackwell'));
define('CONTINUE_READING',__('Continue reading &rarr;', 'blackwell'));
define('PAGES_COLON',__('Pages:', 'blackwell'));
define('CONTINUE_READING_DOTS',__('Continue Reading', 'blackwell'));
define('POSTED_BY',__('Posted by', 'blackwell'));
define('AND_TAGGED',__('and tagged','blackwell'));
define('SMT_MSG',__('Submit Message','blackwell'));
define('CONTACT_NAME',__('Your Name','blackwell'));
define('CONTACT_EMAIL',__('Your Email','blackwell'));
define('CONTACT_MESSAGE',__('Your Message','blackwell'));
define('FORM_SEARCH',__('Search','blackwell'));
define('CMNT_CLSD',__('Comments are closed.','blackwell'));
define('NO_CMNT',__('No Comments','blackwell'));
define('ONE_CMNT',__('One Comments','blackwell'));
define('CMNT',__('Comments','blackwell'));
define('POST_TAGGED_WITH',__('Post Tag With :', 'blackwell'));
define('CONTACT_SUBJECT',__('Subject', 'blackwell'));
define('CONTACT_SUBMIT',__('Send Message', 'blackwell'));
define('HOME_MENU',__('Main Menu', 'blackwell'));
define('FRONT_MENU',__('Front Menu', 'blackwell'));
define('GNL_STG',__('General Settings', 'blackwell'));
define('CTM_FCN',__('Custom Favicon', 'blackwell'));
define('UPL_FCN',__('Here you can upload a Favicon for your Website. Specified size is 16px x 16px.', 'blackwell'));
define('NAME_BLG_PST_RD_MOR',__('Blog Post Read More Text', 'blackwell'));
define('DESC_BLG_PST_RD_MOR',__('Mention the text for blog post read more button', 'blackwell'));
define('TOP_IMG_STTNG',__('Home Page Top Settings', 'blackwell'));
define('NAME_TOP_IMG',__('Home Page Top Image', 'blackwell'));
define('DESC_TOP_IMG',__('The optimal size of the image is 1600px wide x 900px height, but it can be varied as per your requirement.', 'blackwell'));
define('NAME_TOP_HDNG',__('Home Page Top Heading', 'blackwell'));
define('DESC_TOP_HDNG',__('Mention the heading for the Top Image', 'blackwell'));
define('NAME_TOP_LNK',__('Link for Home Page Top Image', 'blackwell'));
define('DESC_TOP_LNK',__('Mention the URL for top image.', 'blackwell'));
define('NAME_TOP_DESC',__('Home Page Top Description', 'blackwell'));
define('DESC_TOP_DESC',__('Mention the Description for home page top area.', 'blackwell'));
define('THREE_FTR_STNG',__('Three Column Feature Setting', 'blackwell'));
define('NAME_T_C_F_HEAD',__('Home Page Three Column Feature Heading', 'blackwell'));
define('DESC_T_C_F_HEAD',__('Mention the heading for your three column feature area on home page.', 'blackwell'));
define('NAME_T_C_F_DESC',__('Home Page Three Column Feature Description', 'blackwell'));
define('DESC_T_C_F_DESC',__('Mention the description for your three column feature area on home page.', 'blackwell'));
define('FST_BLCK',__('First Block', 'blackwell'));
define('NAME_F_F_I',__('First Font Icon', 'blackwell'));
define('DESC_F_F_I',__('Enter the  CSS class fa-cloud  of the icons you want to use on your first column feature. Font Awesome gives you scalable vector icons that can instantly be customized. You can find a list of icon classes here :fortawesome.github.io/Font-Awesome/icons e.g fa-book', 'blackwell'));
define('NAME_F_F_H',__('First Feature Heading', 'blackwell'));
define('DESC_F_F_H',__('Mention the heading for first column that will showcase your business services.', 'blackwell'));
define('NAME_F_F_L',__('First Feature Heading Link', 'blackwell'));
define('DESC_F_F_L',__('Mention the first URL here to redirect the user to any page you want.', 'blackwell'));
define('NAME_F_F_D',__('First Feature Description', 'blackwell'));
define('DESC_F_F_D',__('Write short description for your first heading.', 'blackwell'));
define('SCND_BLCK',__('Second Block', 'blackwell'));
define('NAME_S_F_I',__('Second Font Icon', 'blackwell'));
define('DESC_S_F_I',__('Enter the  CSS class fa-cloud  of the icons you want to use on your second column feature. Font Awesome gives you scalable vector icons that can instantly be customized. You can find a list of icon classes here :fortawesome.github.io/Font-Awesome/icons e.g fa-book', 'blackwell'));
define('NAME_S_F_H',__('Second Feature Heading', 'blackwell'));
define('DESC_S_F_H',__('Mention the heading for second column that will showcase your business services.', 'blackwell'));
define('NAME_S_F_L',__('Second feature Link', 'blackwell'));
define('DESC_S_F_L',__('Mention second the URL here to redirect the user to any page you want.', 'blackwell'));
define('NAME_S_F_D',__('second Feature Description', 'blackwell'));
define('DESC_S_F_D',__('Write short description for your second heading.', 'blackwell'));
define('THRD_BLCL',__('Third block', 'blackwell'));
define('NAME_T_F_I',__('Third Font Icon', 'blackwell'));
define('DESC_T_F_I',__('Enter the  CSS class fa-cloud  of the icons you want to use on your third column feature. Font Awesome gives you scalable vector icons that can instantly be customized. You can find a list of icon classes here :fortawesome.github.io/Font-Awesome/icons e.g fa-book', 'blackwell'));
define('NAME_T_F_H',__('Third Feature Heading', 'blackwell'));
define('DESC_T_F_H',__('Mention the heading for third column that will showcase your business services.', 'blackwell'));
define('NAME_T_F_L',__('Link for Title Third Feature', 'blackwell'));
define('DESC_T_F_L',__('Mention the Third URL here to redirect the user to any page you want.', 'blackwell'));
define('NAME_T_F_D',__('Third Feature Description', 'blackwell'));
define('DESC_T_F_D',__('Write short description for your third heading.', 'blackwell'));
define('HOME_BLOG_STTNG',__('Home Page Blog Setting', 'blackwell'));
define('NAME_B_F_H',__('Home Page Blog Feature Heading', 'blackwell'));
define('DESC_B_F_H',__('Mention the heading for your blog feature area on home page.', 'blackwell'));
define('NAME_B_F_D',__('Home Page Blog Feature Description', 'blackwell'));
define('DESC_B_F_D',__('Mention the description for your blog feature area on home page.', 'blackwell'));
define('THM_OPTN',__('Theme Options', 'blackwell'));
define('SO_FAR',__('so far.', 'blackwell'));
?>